// CONSTANT STRINGS (to avoid typo)
// Entry Names
pub const PRIVATE_PROFILE_ENTRY_NAME: &str = "PRIVATE_PROFILE";
pub const PUBLIC_PROFILE_ENTRY_NAME: &str = "PUBLIC_PROFILE";
// Link Types 
pub const PRIVATE_PROFILE_LINK_TYPE: &str = "PRIVATE_PROFILE_LINK";
pub const PUBLIC_PROFILE_LINK_TYPE: &str = "PUBLIC_PROFILE_LINK";
// Anchor Types
pub const PRIVATE_PROFILES_ANCHOR_TYPE: &str = "PRIVATE_PROFILE";
pub const PUBLIC_PROFILES_ANCHOR_TYPE: &str = "PUBLIC_PROFILE";
// Anchor Text
pub const PRIVATE_PROFILES_ANCHOR_TEXT: &str = "PRIVATE_PROFILES";
pub const PUBLIC_PROFILES_ANCHOR_TEXT: &str = "PUBLIC_PROFILES";