// CONSTANT STRINGS (to avoid typo)
// Entry Names
pub const PRIVATE_PROFILE_ENTRY_NAME: &str = "PRIVATE_PROFILE";
pub const PUBLIC_PROFILE_ENTRY_NAME: &str = "PUBLIC_PROFILE";
pub const HASHED_EMAIL_ENTRY_NAME: &str = "HASHED_EMAIL";
// Link Types 
pub const PRIVATE_PROFILE_LINK_TYPE: &str = "PRIVATE_PROFILE_LINK";
pub const PUBLIC_PROFILE_LINK_TYPE: &str = "PUBLIC_PROFILE_LINK";
pub const HASHED_EMAIL_LINK_TYPE: &str = "HASHED_EMAIL_LINK";
pub const AGENT_PUBLIC_LINK_TYPE: &str = "AGENT->PUBLIC_PROFILE";
pub const AGENT_PRIVATE_LINK_TYPE: &str = "AGENT->PRIVATE_PROFILE";
// Anchor Types
pub const PRIVATE_PROFILES_ANCHOR_TYPE: &str = "PRIVATE_PROFILE_ANCHOR";
pub const PUBLIC_PROFILES_ANCHOR_TYPE: &str = "PUBLIC_PROFILE_ANCHOR";
pub const HASHED_EMAIL_ANCHOR_TYPE: &str = "HASHED_EMAIL_ANCHOR";
// Anchor Text
pub const PRIVATE_PROFILES_ANCHOR_TEXT: &str = "PRIVATE_PROFILES";
pub const PUBLIC_PROFILES_ANCHOR_TEXT: &str = "PUBLIC_PROFILES";
pub const HASHED_EMAIL_ANCHOR_TEXT: &str = "HASHED_EMAILS";



