bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = 'testAgent'
name = 'testAgent'
public_address = 'HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'
test_agent = true

[[dnas]]
file = '/Users/neilsongardose/Documents/projects/beyonder/refork/Kizuna/dnas/lobby/dist/lobby.dna.json'
hash = 'Qmd2QARqTeTzgqpk41jLwuj1wf1YwJq8yoqJ9CoLAqtJFT'
id = 'hc-run-dna'

[[dnas]]
file = 'dna/QmZkb4rzNRe3dxyif9VkNGfhv7YMrdWrC9pK4csEwodJGD.dna.json'
hash = 'QmZkb4rzNRe3dxyif9VkNGfhv7YMrdWrC9pK4csEwodJGD'
id = 'message-dna-HcSci7umev8E78wbdr93P957TYSb3G9SUPvkrOpOK7yxmb7sZfjDHEHk4n8vcpz-HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'test-instance'

[instances.storage]
type = 'memory'

[[instances]]
agent = 'hc-run-agent'
dna = 'message-dna-HcSci7umev8E78wbdr93P957TYSb3G9SUPvkrOpOK7yxmb7sZfjDHEHk4n8vcpz-HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'
id = 'message-instance-HcSci7umev8E78wbdr93P957TYSb3G9SUPvkrOpOK7yxmb7sZfjDHEHk4n8vcpz-HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'

[instances.storage]
path = 'storage/message-instance-HcSci7umev8E78wbdr93P957TYSb3G9SUPvkrOpOK7yxmb7sZfjDHEHk4n8vcpz-HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'
type = 'lmdb'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'test-instance'

[[interfaces.instances]]
id = 'message-instance-HcSci7umev8E78wbdr93P957TYSb3G9SUPvkrOpOK7yxmb7sZfjDHEHk4n8vcpz-HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'

[interfaces.driver]
port = 8888
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
