bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = 'testAgent'
name = 'testAgent'
public_address = 'HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'
test_agent = true

[[dnas]]
file = '/Users/tats/projects/Kizuna/dna/dist/dna.dna.json'
hash = 'QmaXFiW7mcAwuvJhLZgNZNAoZAVT4faJLFhnxcAMehNeR3'
id = 'hc-run-dna'

[[dnas]]
file = 'dna/QmVVPaAnthDtgSUCfFy2RBARSdVEHYAeLakC8aq6TBHTT1.dna.json'
hash = 'QmVVPaAnthDtgSUCfFy2RBARSdVEHYAeLakC8aq6TBHTT1'
id = 'dna-dos'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'test-instance'

[instances.storage]
type = 'memory'

[[instances]]
agent = 'hc-run-agent'
dna = 'dna-dos'
id = 'test-instance-dos'

[instances.storage]
path = 'storage/test-instance-dos'
type = 'lmdb'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'test-instance'

[[interfaces.instances]]
id = 'test-instance-dos'

[interfaces.driver]
port = 8888
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
