// CONSTANT STRINGS (to avoid typo)
// Entry Names
const PRIVATE_PROFILE_ENTRY_NAME: &str = "PRIVATE_PROFILE";
const PUBLIC_PROFILE_ENTRY_NAME: &str = "PUBLIC_PROFILE";
// Link Types 
const PRIVATE_PROFILE_LINK_TYPE: &str = "PRIVATE_PROFILE_LINK";
const PUBLIC_PROFILE_LINK_TYPE: &str = "PUBLIC_PROFILE_LINK";
// Anchor Types
const PRIVATE_PROFILES_ANCHOR_TYPE: &str = "PRIVATE_PROFILE";
const PUBLIC_PROFILES_ANCHOR_TYPE: &str = "PUBLIC_PROFILE";
// Anchor Text
const PRIVATE_PROFILES_ANCHOR_TEXT: &str = "PRIVATE_PROFILES";
const PUBLIC_PROFILES_ANCHOR_TEXT: &str = "PUBLIC_PROFILES";